---
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
title: 'Results on simulation data'
output:
  html_document:
    toc: true
    toc_float: TRUE
    toc_depth: 2
    number_sections: true
    code_download: TRUE
---

```{r load packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = F, message = F,
  fig.align = "center", echo = F
)
libs <- c("here", "dplyr", "ggplot2", "tidyr", "stringr", "readr", "cowplot",
          "mclust", "RColorBrewer", "purrr", "Dune", "pracma", "purrr",
          "DailyHRB", "patchwork")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
```

# Getting the mapping results

```{r}
df <- bind_rows("Pancreas" = read.csv(here("Mapping", "Data", "Pancreas.csv")),
                "Brain" = read.csv(here("Mapping", "Data", "Brain.csv")),
                .id = "pair") %>%
  pivot_longer(c("imp", "imp_prop"), names_to = "Type", values_to = "proba")
```

```{r}
ggplot(df, aes(x = proba, fill = pair)) +
  geom_histogram(position = "dodge", bins = 50) +
  my_theme() +
  facet_wrap(~Type) +
  scale_fill_brewer(type = "qual")
```

```{r}
df %>%
  group_by(pair, Type) %>%
  summarise(imp = mean(proba > 0),
            mean_imp = mean(proba))
```