---
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
title: 'Results on simulation data'
output:
  html_document:
    toc: true
    toc_float: TRUE
    toc_depth: 2
    number_sections: true
    code_download: TRUE
---

```{r load packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = F, message = F,
  fig.align = "center", echo = F
)
libs <- c("here", "dplyr", "ggplot2", "tidyr", "stringr", "readr", "cowplot",
          "mclust", "RColorBrewer", "purrr", "Dune", "pracma", "purrr",
          "DailyHRB", "patchwork")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
```

# Pancreas

```{r}
Pancreas <- read.csv(here("DE", "Data", "Pancreas.csv")) %>%
  rename("method_1" = "X") %>%
  pivot_longer(-method_1, values_to = "Dist", names_to = "method_2") %>%
  group_by(method_1, method_2) %>%
  mutate(first = min(method_1, method_2),
         second = max(method_1, method_2)) %>%
  ungroup() %>%
  select(first, second, Dist) %>%
  distinct() %>%
  filter(word(first, 2, sep = "\\.") == word(second, 2, sep = "\\."),
         Dist != 1) %>%
  mutate(level = word(first, 2, sep = "\\."),
         first = word(first, 1, sep = "\\."),
         second = word(second, 1, sep = "\\."),
         same_dataset = word(first, 1, sep = "_") == word(second, 1, sep = "_"),
         same_comp = word(first, 2, sep = "_") == word(second, 2, sep = "_"),
         same_method = word(first, 3, sep = "_") == word(second, 3, sep = "_"),
         level = if_else(level == "00", "Initial", "Final")) %>%
  # filter(same_dataset == TRUE) %>%
  pivot_wider(names_from = "level", values_from = "Dist")
ggplot(Pancreas, aes(x = Initial, y = Final, color = same_method)) +
  geom_jitter() +
  facet_wrap(~same_dataset, scales = "free")
```

# Brain

```{r}
Brain <- read.csv(here("DE", "Data", "Brain.csv")) %>%
  rename("method_1" = "X") %>%
  pivot_longer(-method_1, values_to = "Dist", names_to = "method_2") %>%
  group_by(method_1, method_2) %>%
  mutate(first = min(method_1, method_2),
         second = max(method_1, method_2)) %>%
  ungroup() %>%
  select(first, second, Dist) %>%
  distinct() %>%
  filter(word(first, 2, sep = "\\.") == word(second, 2, sep = "\\."),
         Dist != 1) %>%
  mutate(level = word(first, 2, sep = "\\."),
         first = word(first, 1, sep = "\\."),
         second = word(second, 1, sep = "\\."),
         same_dataset = word(first, 1, sep = "_") == word(second, 1, sep = "_"),
         same_comp = word(first, 2, sep = "_") == word(second, 2, sep = "_"),
         same_method = word(first, 3, sep = "_") == word(second, 3, sep = "_"),
         level = if_else(level == "00", "Initial", "Final")) %>%
  # filter(same_dataset == TRUE) %>%
  pivot_wider(names_from = "level", values_from = "Dist")
ggplot(Pancreas, aes(x = Initial, y = Final, color = same_method)) +
  geom_jitter() +
  facet_wrap(~same_dataset, scales = "free")
```