---
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
title: "Dune's inner workings"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: TRUE
    number_sections: true
    code_download: TRUE
---

```{r load packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = F, message = F,
  fig.width = 5, fig.align = "center", echo = F
)
libs <- c("here", "dplyr", "ggplot2", "tidyr", "stringr", "readr", "cowplot",
          "clusterExperiment", "mclust", "RColorBrewer", "Dune", "purrr",
          "DailyHRB")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
mergers <- readRDS(here("Brain", "data", "Dune",
                        "SMARTer_nuclei_MOp_NMI_mergers.rds"))
tSNE <- read.csv(here("Brain", "data", "tSNE", "SMARTer_cells_MOp_tnse.csv")) %>%
  select(-X)
```

# Initial confusion matrices

```{r}
p1 <- ConfusionPlot(mergers$initialMat[, c("sc3", "Monocle")]) +
  labs(x = "Partition 1", y = "Partition 2") + 
  scale_color_gradientn(colours = brewer.pal(11, "Spectral"),
                        limits = c(0, 1)) +
  scale_size_continuous(breaks = c(0, 250, 500, 750, 1000),
                        limits = c(0, 1100)) 
legend_common <- get_legend(
  p1 +
    theme(legend.position = "bottom") +
    guides(size = guide_legend(title.position = "top", fill = "grey",
                               title.hjust = .5),
           col = guide_colourbar(title.position = "top", title.hjust = .5)) +
    theme(legend.margin = margin(0, 0, 0, 0),
          legend.text = element_text(size = 5))
  )
legend_common <- plot_grid(legend_common)
ggsave(plot = legend_common,
       filename = here("Figure-Dune", "figures", "legend.png"),
       bg = "transparent", width = 7, height = 2)
p1 <- p1 + guides(col = FALSE, size = FALSE) +
  theme(axis.title = element_text(size = 18))
p11 <- p1
p11
ggsave(plot = p1, filename = here("Figure-Dune", "figures",
                                  "confusion_plot_before_1.png"),
       bg = "transparent", width = 5, height = 5)
p2 <- ConfusionPlot(mergers$initialMat[, c("sc3", "Seurat")]) +
  labs(x = "SC3", y = "Seurat") +
  scale_color_gradientn(colours = brewer.pal(11, "Spectral"),
                        limits = c(0, 1)) +
  scale_size_continuous(breaks = c(100, 200, 300, 400, 600)) +
  guides(col = FALSE, size = FALSE)
ggsave(plot = p2, filename = here("Figure-Dune", "figures",
                                  "confusion_plot_before_2.png"),
       bg = "transparent", width = 5, height = 5)
p3 <- ConfusionPlot(mergers$initialMat[, c("Seurat", "Monocle")]) +
  labs(x = "Seurat", y = "Monocle") +
  guides(col = FALSE, size = FALSE) +
  scale_color_gradientn(colours = brewer.pal(11, "Spectral"),
                        limits = c(0, 1)) +
  scale_size_continuous(breaks = c(100, 200, 300, 400, 600))
ggsave(plot = p3, filename = here("Figure-Dune", "figures",
                                  "confusion_plot_before_3.png"),
       bg = "transparent", width = 5, height = 5)
rm(p1, p2, p3)
```

# 2d plot of overlap

```{r}
overlap <- table(mergers$initialMat$sc3, mergers$initialMat$Monocle) %>%
    as.data.frame() %>%
    group_by(Var1) %>%
    mutate(total_x = sum(Freq)) %>%
    group_by(Var2) %>%
    mutate(total_y = sum(Freq),
           union = total_x + total_y - Freq,
           overlap = Freq / union) %>%
    ungroup() %>%
    arrange(desc(Freq)) %>%
    filter(Freq > 0)
df <- mergers$initialMat %>% mutate(cells = rownames(.)) %>%
  inner_join(tSNE) %>%
  mutate(sc3 = as.character(sc3),
         Monocle = as.character(Monocle)) %>%
  inner_join(overlap, by = c("sc3" = "Var1", "Monocle" = "Var2"))

p <- ggplot(df, aes(x = x, y = y, col = overlap)) +
  geom_point(size = .8, alpha = .7) +
  my_theme() +
  labs(x = "t-SNE 1", y = "t-SNE 2", col = "Jaccard Index") +
  scale_color_gradientn(colours = brewer.pal(11, "Spectral"))
p
ggsave(plot = p, filename = here("Figure-Dune", "figures", "2d.png"),
       bg = "transparent", width = 9, height = 7)
```

# Improvement in NMI

```{r NMI imp no allen cell}
p1 <- plotNMIs(mergers$initialMat) +
  labs(x = "", y = "") +
  theme(plot.title = element_text(hjust = 0.5),
        rect = element_blank()) +
   theme(axis.text = element_text(size = 10)) +
  scale_y_discrete(limits = c("Seurat", "sc3", "Monocle"),
                   labels = c("Partition 3", "Partition 2", "Partition 1")) +
  scale_x_discrete(labels = c("Partition 1", "Partition 2", "Partition 3"))
p1
p12 <- p1
ggsave(plot = p1, filename = here("Figure-Dune", "figures", 
                                  "NMI_Matrix_Before.png"),
       bg = "transparent", width = 7, height = 7)
p2 <- plotNMIs(mergers$currentMat) +
  labs(x = "", y = "") +
  theme(plot.title = element_text(hjust = 0.5),
        rect = element_blank()) +
   theme(axis.text = element_text(size = 10)) +
  scale_y_discrete(limits = c("Seurat", "sc3", "Monocle"),
                   labels = c("Partition 3", "Partition 2", "Partition 1")) +
  scale_x_discrete(labels = c("Partition 1", "Partition 2", "Partition 3"))
p2
p22 <- p2
ggsave(plot = p2, filename = here("Figure-Dune", "figures", 
                                  "NMI_Matrix_After.png"),
       bg = "transparent", width = 7, height = 7)
```

# Confusion matrices after merging

```{r}
p1 <- ConfusionPlot(mergers$currentMat[, c("sc3", "Monocle")]) +
  labs(x = "Partition 1", y = "Partition 2") + 
  scale_color_gradientn(colours = brewer.pal(11, "Spectral"),
                        limits = c(0, 1)) +
  scale_size_continuous(limits = c(0, 1100)) +
  theme(legend.margin = margin(0, 0, 0, 0)) +
  guides(col = FALSE, size = FALSE) +
  theme(axis.title = element_text(size = 18))
p21 <- p1 
p21
ggsave(plot = p1, filename = here("Figure-Dune", "figures",
                                  "confusion_plot_after_1.png"),
       bg = "transparent", width = 5, height = 5)
p2 <- ConfusionPlot(mergers$currentMat[, c("sc3", "Seurat")]) +
  labs(x = "Sc3", y = "Seurat") +
  guides(col = FALSE, size = FALSE) +
  scale_color_gradientn(colours = brewer.pal(11, "Spectral"),
                        limits = c(0, 1)) +
  scale_size_continuous(breaks = c(100, 200, 300, 400, 600))
ggsave(plot = p2, filename = here("Figure-Dune", "figures",
                                  "confusion_plot_after_2.png"),
       bg = "transparent", width = 5, height = 5)
p3 <- ConfusionPlot(mergers$currentMat[, c("Seurat", "Monocle")]) +
  labs(x = "Seurat", y = "Monocle") +
  guides(col = FALSE, size = FALSE) +
  scale_color_gradientn(colours = brewer.pal(11, "Spectral"),
                        limits = c(0, 1)) +
  scale_size_continuous(breaks = c(100, 200, 300, 400, 600))
ggsave(plot = p3, filename = here("Figure-Dune", "figures",
                                  "confusion_plot_after_3.png"),
       bg = "transparent", width = 5, height = 5)
rm(p1, p2, p3)
```

# Trend of NMI improvements and number of clusters

```{r NMI trend}
NMI <- NMIImp(mergers)
df <- data.frame(step = 0:length(mergers$ImpMetric),
                 NMI = NMI)
p13 <- ggplot(df, aes(x = step, y = NMI)) +
  geom_path(size = 2) +
  scale_x_continuous(breaks = c(0, length(mergers$ImpMetric)),
                       labels = c("Initial", "Final"))  +
  theme_classic() +
  theme(rect = element_blank()) +
  labs(x = "Merging steps", y = "mean NMI between partitions")
ggsave(plot = p13, width = 6, height = 6,
       filename = here("Figure-Dune", "figures", "NMI-imp.png"),
       bg = "transparent")
p13
```

```{r}
baseMat <- mergers$initialMat
f <- function(clusMat, i) dplyr::n_distinct(clusMat[, i])
n_clus <- data.frame("Partition 1" = functionTracking(mergers, f, i = 2),
                     "Partition 2" = functionTracking(mergers, f, i = 3),
                     "Partition 3" = functionTracking(mergers, f, i = 4))
df <- data.frame(step = 0:length(mergers$ImpMetric),
                 n_clus) %>%
  pivot_longer(-step, values_to = "n_clus", names_to = "Partition") %>%
  mutate(Partition = str_replace_all(Partition, "\\.", " "))
p23 <- ggplot(df,
            aes(x = step, y = n_clus, col = Partition, group = Partition)) +
  geom_path(size = 2, alpha = .7) +
  scale_x_continuous(breaks = c(0, length(mergers$ImpMetric)),
                       labels = c("Initial", "Final"))  +
  theme_classic() +
  theme(rect = element_blank()) +
  labs(x = "Merging steps", y = "Number of clusters", col = "") +
  scale_color_brewer(palette = "Set1") +
  guides(col = guide_legend(override.aes = list(alpha = 1))) +
  theme(legend.position = c(.85, .8),
        legend.title.align = 0.5)
ggsave(plot = p23, width = 6, height = 2 * 7 / 3,
       filename = here("Figure-Dune", "figures", "number_clusters.png"),
       bg = "transparent")
p23
```

```{r}
first_row <- plot_grid(ggdraw() +
      draw_image(here("Figure-Dune", "figures", "confusion_plot_before_1.png")),
      p12, p13, ggdraw() +
      draw_image(here("Figure-Dune", "figures", "legend.png"), scale = 1.5),
      labels = c('a)', 'b)', 'c)', ''), label_size = 18, ncol = 3, 
      scale = .95, rel_heights = c(1, .3), rel_widths = c(1, 1, 1))

second_row <- plot_grid(ggdraw() +
      draw_image(here("Figure-Dune", "figures", "confusion_plot_after_1.png")),
      p22, p23, labels = c('d)', 'e)', 'f)'), label_size = 18, scale = .95,
      ncol = 3)

# third_row <- plot_grid(p31, p32, labels = c('e)', 'f)'), label_size = 10,
#                      scale = .95)

p <- plot_grid(first_row, second_row,
               # third_row,
               ncol = 1, rel_heights = c(1.3, 1))
save_plot(plot = p, 
          filename = here("Figure-Dune", "figures", "panel.png"),
          base_width = 10, base_height = 7.5,
          bg = "transparent")
```

