---
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
title: 'Panel on Dune specificities'
output:
  html_document:
    toc: true
    toc_float: TRUE
    toc_depth: 2
    number_sections: true
    code_download: TRUE
---

```{r load packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = F, message = F,
  fig.align = "center", echo = F
)
libs <- c("here", "dplyr", "ggplot2", "tidyr", "stringr", "readr", "cowplot",
          "mclust", "RColorBrewer", "purrr", "Dune", "pracma", "purrr",
          "DailyHRB")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
```

# Garbage Replicability

```{r}
df <- read.table(here("Figure-Stability", "data", "garbage.txt")) %>%
  mutate(nb_clusters = (replicable_clusters + non_replicable_clusters) / 2) %>%
  group_by(Comp, rep, nb_garb, clustering_name) %>%
  arrange(level) %>%
  summarise(AURC = -trapz(x = nb_clusters, y = fraction_replicable_clusters)) %>%
  ungroup() %>%
  group_by(Comp, nb_garb, clustering_name) %>%
  summarise(AURC = mean(AURC)) %>%
  ungroup() %>%
  group_by(Comp, clustering_name) %>%
  arrange(nb_garb) %>%
  mutate(AURC = AURC / first(AURC)) %>%
  identity()
p1 <- ggplot(df, aes(x = nb_garb, y = 100 * AURC, group = nb_garb)) +
  geom_boxplot() +
  my_theme() +
  scale_y_continuous(limits = c(80, 120), 
                     breaks = 8:12 * 10,
                     labels = paste(8:12 * 10, "%")) +
  labs(x = "Number of random inputs",
       y = "Ratio of AURC over\nAURC with no random inputs") +
  # theme() +
  NULL
p1
ggsave(filename = here("Figure-Stability", "figures", "garbage.png"),
       bg = "transparent", plot = p1)
```

# Stability to downsampling

```{r}
df <- read.table(here("Figure-Stability", "data", "downsampling.txt")) %>%
  mutate(nb_clusters = (replicable_clusters + non_replicable_clusters) / 2) %>%
  group_by(Comp, fraction, clustering_name) %>%
  arrange(level) %>%
  summarise(AURC = -trapz(x = nb_clusters, y = fraction_replicable_clusters)) %>%
  ungroup() %>%
  group_by(Comp, clustering_name) %>%
  arrange(desc(fraction)) %>%
  mutate(AURC = AURC / first(AURC))
p3 <- ggplot(df, aes(x = fraction, y = 100 * AURC)) +
  geom_boxplot(aes(group = fraction), outlier.shape = NA, width = 4) +
  my_theme() +
  scale_y_continuous(limits = c(25, 170),
                     breaks = 1:4 * 40,
                     labels = paste(1:4 * 40, "%")) +
  scale_x_continuous(breaks = c(1, 5, 1:10 * 10)) +
  labs(x = "Fraction of cells used as input for Dune",
       y = "Ratio of AURC over\nAURC with the full dataset") +
  # theme() +
  NULL
p3
# ggsave(filename = here("Figure-Stability", "figures", "down.png"),
       # bg = "transparent", plot = p3)
```

# Dune's stoppping point is meaningfull

```{r}
mergers <- readRDS(here("Brain", "data", "Dune",
                        "SMARTer_nuclei_MOp_mergers.rds"))
allen_clusters <- read.csv(here("Brain", "data", "Smart-Seq",
                                  "SMARTer_nuclei_MOp_cluster.membership.csv"),
                           col.names = c("cells", "cluster_id"))
clusters <- read.csv(here("Brain", "data", "Smart-Seq",
                          "SMARTer_nuclei_MOp_cluster.annotation.csv"),
                       header = T)
allen_clusters <- full_join(allen_clusters, clusters) %>%
  arrange(cells) %>%
  mutate(cells = as.character(cells)) %>%
  filter(class_label != "Noise") %>%
  arrange(class_label)
allen_clusters$subclass_label <- factor(allen_clusters$subclass_label,
                                levels = unique(allen_clusters$subclass_label))
rm(clusters)

p2 <- ConfusionPlot(y = mergers$currentMat[allen_clusters$cells, "sc3"],
                    x = allen_clusters$subclass_label) +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(rect = element_blank()) +
  labs(x = "Allen Subclass Labels", y = "SC3 merged with Dune")
p2
ggsave(filename = here("Figure-Stability", "figures", "Stoppping_Point.png"),
       plot = p2, bg = "transparent", width = 7, height = 7)
```


```{r}
df <- bind_rows(
  read.table(here("Figure-Stability", "data", "Brain-methods.txt"),
             header = TRUE),
  read.table(here("Figure-Stability", "data", "Pancreas-methods.txt"),
             header = TRUE)
)
df <- df %>% 
  pivot_longer(-c("steps", "dataset"), names_to = "methods",
               values_to = "meanARI") %>%
  group_by(dataset, methods) %>%
  arrange(steps) %>%
  summarise(begin = first(meanARI),
            end = last(meanARI)) %>%
  group_by(dataset) %>%
  summarise(begin = mean(begin), end = mean(end))
```

# Panel

```{r, eval = F}
top_row <- plot_grid(p1, p3, labels = c('a)', 'b)'), label_size = 15,
                     scale = .9)
second_row <- plot_grid(NULL, p2 + theme(legend.position = "right") +
                        guides(col = 
                                 guide_colourbar(title.position = "top",
                                                 barwidth = unit(.05, "npc"))),
                        NULL, labels = c('', 'c)', ''), label_size = 15,
                        ncol = 3, rel_widths = c(3, 7, 1), scale = .9)

p <- plot_grid(top_row, second_row, label_size = 15, ncol = 1)
ggsave(filename = here("Figure-Stability", "figures", "panel.png"),
       bg = "transparent", plot = p, width = 11, height = 8)
```

```{r}
second_column <- plot_grid(p1, p3, labels = c('b)', 'c)'), label_size = 15,
                     scale = .9, ncol = 1)
first_colum <- plot_grid(p2 +
                           theme(legend.position = c(.5, -.35),
                                 legend.box = 'vertical') +
  guides(col = guide_colourbar(title.position = "top",
                               barheight = unit(.05, "npc"),
                               barwidth = unit(.4, "npc"),
                               direction = "horizontal"),
         size = guide_legend(direction = "horizontal")),
                         NULL,
                         labels = c('a)', ''), label_size = 15,
                         ncol = 1, rel_heights = c(7, 2),
                         scale = .9)

p <- plot_grid(first_colum, second_column, label_size = 15, ncol = 2)
p
ggsave(filename = here("Figure-Stability", "figures", "panel.png"),
       bg = "transparent", plot = p, width = 11, height = 8)
```