---
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
title: 'Impact of all the methods on ARI merging'
output:
  html_document:
    toc: true
    toc_float: TRUE
    toc_depth: 2
    number_sections: true
    code_download: TRUE
---

```{r load packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = F, message = F,
  fig.align = "center", echo = F
)
libs <- c("here", "dplyr", "ggplot2", "tidyr", "stringr", "readr", "cowplot",
          "mclust", "RColorBrewer", "purrr", "Dune", "pracma", "kableExtra",
          "DailyHRB", "cowplot", "latex2exp")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
```

# Panel a

```{r}
df <- read.table(here("Figure-ARI", "data", "sc3-comp1.txt"), header = TRUE,
                       stringsAsFactors = FALSE) %>% filter(mergeMethod != "Params")
p1 <- ggplot(df, aes(x = n_clus, y = ARI, col = mergeMethod)) +
  geom_line(size = 2, alpha = .9,
            arrow = arrow(length = unit(0.30,"cm"), ends = "first", 
                          type = "closed"),
            show.legend = FALSE) +
  geom_line(size = 0, alpha = 0) +
  my_theme() +
  scale_color_brewer(palette = "Dark2") +
  annotate("text", x = max(df$n_clus), y = min(df$ARI) + .03,
           label = "Start", fontface = "bold", size = 4) +
  labs(x = "Number of clusters", y = "ARI with gold standard",
       col = "Method of\nmerging") +
  scale_x_continuous(breaks = c(20, 25, 30)) +
  guides(color = guide_legend(
    reverse = TRUE,
    override.aes = list(size = 2, alpha = 1))
  ) +
  theme(legend.position = c(.9, .8),
        legend.title.align = 0.5,
        legend.title = element_text(size = 17),
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 10),
        legend.text = element_text(size = 12))
p1
ggsave(plot = p1, filename = here("Figure-ARI", "figures", "sc3-example.png"),
       bg = "transparent", width = 7, height = 7)
```

# Panel b

```{r}
df2 <- df %>% filter(mergeMethod == "Dune")
p2 <- ggplot(df2, aes(x = n_clus, y = ARI)) +
  geom_ribbon(aes(ymax = ARI), ymin = min(df$ARI) - 5,
              fill = "gray", alpha = .5) +
  geom_line(size = 2, col = "#7570B3") +
  my_theme() +
  geom_segment(x = min(df2$n_clus), xend = max(df2$n_clus), y = 0, yend = 0) +
  geom_segment(x = min(df2$n_clus), xend = min(df2$n_clus), y = 0,
               yend = df2$ARI[1]) +
  geom_segment(x = max(df2$n_clus), xend = max(df2$n_clus), y = 0,
               yend = df2$ARI[nrow(df2)]) +
  annotate("text", x = (min(df2$n_clus) + max(df2$n_clus)) / 2,
           y = .66 * min(df$ARI) + .33 * max(df$ARI),
           label = "Area Under the ARI Curve\n(AUARIC)",
           size = 5) +
  labs(x = "Number of clusters", y = "ARI with gold standard") +
  scale_x_continuous(breaks = c(20, 25, 30)) +
  scale_y_continuous(limits = c(min(df$ARI), max(df$ARI))) +
  theme(axis.title = element_text(size = 15),
        axis.text = element_text(size = 10),
        legend.text = element_text(size = 10))
p2
ggsave(plot = p2, filename = here("Figure-ARI", "figures", "AUARIC.png"),
       bg = "transparent", width = 7, height = 7)
```

# Panel c

```{r}
types <- unique(df$mergeMethod)
names(types) <- types
AUARIC <- map_df(types, function(type){
  df <- df %>% 
    filter(mergeMethod == type) %>%
    arrange(n_clus)
  return(trapz(x = df$n_clus, y = df$ARI))
}) %>%
  t() %>%
  as.data.frame() %>%
  mutate("mergeMethods" = rownames(.)) %>%
  select(mergeMethods, V1) %>%
  filter(mergeMethods != "Params") %>%
  dplyr::rename(AUARIC = V1,
         "Methods of\nmerging" = "mergeMethods")
AUARIC$`scaled AUAIRC` <- scale(AUARIC$AUARIC)
  
kableExtra::kable(AUARIC, format = "html", digits = 2) %>%
  kable_styling("striped") %>%
  column_spec(1:2, width = "1cm")
```

# Panel d

```{r}
df <- bind_rows(
  "Brain" = read.table(here("Figure-ARI", "data", "Brain.txt"), header = TRUE,
                       stringsAsFactors = FALSE),
  "Pancreas" = read.table(here("Figure-ARI", "data", "Pancreas.txt"),
                          header = TRUE, stringsAsFactors = FALSE)
  ) %>%
  mutate(dataset = 
           case_when(dataset == "SMARTer_cells_MOp" ~ "AIBS scRNA-Smart",
                     dataset == "SMARTer_nuclei_MOp" ~ "AIBS snRNA-Smart",
                     TRUE ~ dataset)) %>%
  mutate(scenario = paste0(dataset, "\n", method, "_", comp))
  
df <- df %>% arrange(scenario)
rank <- df %>%
  group_by(scenario) %>%
  filter(Merge_method != "Param") %>%
  mutate(rk = rank(dplyr::desc(AUARIC))) %>%
  ungroup() %>%
  select(Merge_method, rk) %>%
  table
  
labels <- paste0(str_replace_all(df$dataset, "_", "-"), "\n", df$method,
                 "-$\\Theta_", 1:3, "$") %>%
  unique()
labels <- lapply(lapply(labels, TeX), function(text) {parse(text = text)}) %>%
  unlist()
p3 <- ggplot(df %>% select(scenario, Merge_method, AUARIC) %>%
              group_by(scenario) %>%
              filter(Merge_method != "Param") %>%
              mutate(AUARIC = scale(AUARIC)),
            aes(x = scenario, y = Merge_method, fill = AUARIC)) +
  geom_tile() +
  scale_fill_viridis_c(begin = 1, end = 0) +
  # scale_fill_gradientn(colors = brewer.pal(9, "Spectral")[9:1]) +
  my_theme() +
  theme(axis.text.x = element_text(angle = 90),
        axis.line = element_blank()) +
  labs(x = "", y = "", fill = "Scaled\nAUARIC",
       title = bquote("3 clustering methods × 3" ~ Theta ~
                        " × 4 datasets = 36 comparisons")) +
  theme(axis.text.y = element_text(size = 15),
        axis.text.x = element_text(size = 8),
        legend.title = element_text(size = 14, hjust = .5),
        title = element_text(size = 18)) +
  # scale_x_discrete(labels = labels) +
  NULL
p3
ggsave(plot = p3, filename = here("Figure-ARI", "figures", "all_comp.png"),
       width = 14, height = 3,
       bg = "transparent")
```

# Panel 

```{r}
# first align the top-row plot (p3) with the left-most plot of the
# bottom row (p1)
plots <- align_plots(p1, p3 + theme(legend.position = "bottom"),
                     align = 'v', axis = 'l')
# then build the top row
top_row <- plot_grid(plots[[1]], p2, labels = c('a)', 'b)'), label_size = 18,
                     scale = .8)

# then combine with the top row for final plot
p <- plot_grid(top_row, plots[[2]], labels = c('', 'c)'), label_size = 18,
               ncol = 1, rel_heights = c(2, 1.5))
save_plot(plot = p, 
          filename = here("Figure-ARI", "figures", "panel.png"),
          base_width = 12, base_height = 9,
          bg = "transparent")
```

```{r with patchwork}
library(patchwork)
patch <- 
  ((p1 | plot_spacer() | p2) + plot_layout(widths = c(1, .1, 1))) /
  (p3 + theme(legend.position = "bottom")) +
  plot_layout(heights = c(3, 1)) +
  plot_annotation(tag_levels = 'a') & 
  theme(plot.tag = element_text(size = 20),
        rect = element_blank())
save_plot(plot = patch, 
          filename = here("Figure-ARI", "figures", "panel2.png"),
          base_width = 12, base_height = 8,
          bg = "transparent")  


```