---
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
title: 'Results on simulation data'
output:
  html_document:
    toc: true
    toc_float: TRUE
    toc_depth: 2
    number_sections: true
    code_download: TRUE
---

```{r load packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = F, message = F,
  fig.align = "center", echo = F
)
libs <- c("here", "dplyr", "ggplot2", "tidyr", "stringr", "readr", "cowplot",
          "mclust", "RColorBrewer", "purrr", "Dune", "pracma", "purrr",
          "DailyHRB", "patchwork")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
```

# Finding the best out of all threes
## Simulations

```{r best agreement}
mean_method <- lapply(1:5, function(id) {
  df <- read.csv(here("Simulations", "Data", paste0("Dune_", id, ".csv"))) %>%
    select("SC3.100", "UMAP_KMEANS.100", "TSNE_KMEANS.100")
  colnames(df) <- word(colnames(df), 1, sep = "\\.") %>% unlist()
  NMI <- NMIs(as.matrix(df)) %>% colMeans()
  return(data.frame(clustering = names(NMI),
                    Metric = "MeanNMI",
                    Value = NMI))
}) %>% 
  bind_rows(.id = "Dataset")
```

```{r best performing}
res <- lapply(1:5, function(id){
  df <- read.csv(here("Simulations", "Data", paste0("Metric_Ref_", id, ".csv")))
  df <- df %>%
    filter(method == "Dune_NMI",
           level == 100) %>%
    select(clustering, Metric, Value)
  return(df)
}) %>%
  bind_rows(.id = "Dataset")
res <- bind_rows(mean_method, res)
rm(mean_method)
```

```{r}
plots <- list()
i <- 1
for (Eval in c("ARI", "NMI")) {
  for (Crit in c("SL", "MeanNMI")) {
    df <- res %>%
      filter(Metric %in% c(Eval, Crit)) %>%
      arrange(Metric) %>%
      pivot_wider(names_from = "Metric", values_from = "Value")
    colnames(df)[3:4] <- c("Eval", "Crit")[order(c(Eval, Crit))]
    p <- ggplot(df, aes(x = Eval, y = Crit, col = clustering)) +
      geom_point() +
      labs(x = Eval, y = Crit) +
      facet_wrap(~Dataset, scales = "free") +
      DailyHRB::my_theme()
    plots[[i]] <- p + guides(col = FALSE)
    i <- i + 1
  }
}
plot_grid(plotlist = plots, nrow = 2)
rm(Crit, Eval, i, plots, df, p)
```
```{r}
g1 <- df <- res %>% pivot_wider(names_from = Metric, values_from = Value) %>%
  pivot_longer(c(NMI, ARI), names_to = "EvalMetric", values_to = "Evaluation") %>%
  pivot_longer(c(SL, MeanNMI), names_to = "SelectMetric", values_to = "Selection") %>%
  group_by(Dataset, EvalMetric, SelectMetric) %>%
  mutate(Evaluation = rank(Evaluation) %>% as.integer(),
         Selection = rank(Selection) %>% as.integer()) %>%
  ungroup() %>%
  filter(Selection == 1) %>%
  group_by(EvalMetric, SelectMetric) %>%
  summarise(best = 100 * mean(Evaluation == 1),
            second = 100 * mean(Evaluation == 2),
            third = 100 * mean(Evaluation == 3))
```

## Brain

```{r}
df <- read.table(here("BestMethod", "Data", "Brain.txt"), header = TRUE) %>%
  pivot_wider(names_from = "Metric", values_from = "Value") %>%
  pivot_longer(c("MeanNMI", "SL"), values_to = "Selection", names_to = "SelectMetric") %>%
  pivot_longer(c("ARI", "Rep"), values_to = "Evaluation", names_to = "EvalMetric")
```


```{r}
ggplot(df, aes(x = Evaluation, y = Selection, col = comp)) +
  geom_point() +
  labs(x = "Evaluation", y = "Selection") +
  facet_grid(EvalMetric + SelectMetric ~ dataset, scales = "free") +
  theme_bw()
```
```{r}
g2 <- df %>%
  group_by(dataset, EvalMetric, SelectMetric, comp) %>%
  mutate(Evaluation = rank(Evaluation) %>% as.integer(),
         Selection = rank(Selection) %>% as.integer()) %>%
  ungroup() %>%
  filter(Selection == 1) %>%
  group_by(EvalMetric, SelectMetric) %>%
  summarise(best = 100 * mean(Evaluation == 1),
            second = 100 * mean(Evaluation == 2),
            third = 100 * mean(Evaluation == 3))
```


## Pancreas

```{r}
df <- read.table(here("BestMethod", "Data", "Pancreas.txt"), header = TRUE)  %>%
  pivot_wider(names_from = "Metric", values_from = "Value") %>%
  pivot_longer(c("MeanNMI", "SL"), values_to = "Selection", names_to = "SelectMetric") %>%
  pivot_longer(c("ARI", "Rep"), values_to = "Evaluation", names_to = "EvalMetric")
```


```{r}
ggplot(df, aes(x = Evaluation, y = Selection, col = comp)) +
  geom_point() +
  labs(x = "Evaluation", y = "Selection") +
  facet_grid(EvalMetric + SelectMetric ~ dataset, scales = "free") +
  theme_bw()
```

```{r}
g3 <-df %>%
  group_by(dataset, EvalMetric, SelectMetric, comp) %>%
  mutate(Evaluation = rank(Evaluation) %>% as.integer(),
         Selection = rank(Selection) %>% as.integer()) %>%
  ungroup() %>%
  filter(Selection == 1) %>%
  group_by(EvalMetric, SelectMetric) %>%
  summarise(best = 100 * mean(Evaluation == 1),
            second = 100 * mean(Evaluation == 2),
            third = 100 * mean(Evaluation == 3))
```

# Results

```{r}
df <- bind_rows("Simulations" = g1,
                "Brain" = g2, 
                "Pancreas" = g3,
                .id = "Dataset") %>%
  arrange(SelectMetric, EvalMetric)
knitr::kable(df)
```