---
title: "Replicability comparison"
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = F, message = F,
  fig.align = "center", echo = F
)
libs <- c("here", "tidyverse", "DailyHRB")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
```


```{r laod data}
read_single_method <- function(Method,
                               result_dir = here("Brain", "data",
                                                 "Replicability", 
                                                 "SingleMethod", "smart")) {
  df <- read.table(file.path(result_dir, "consensus_cluster_replicability.txt"))
  df <- df %>% filter(clustering_name == Method)
}

Seurat <- read_single_method(Method = "Seurat") %>% 
  mutate(level = str_extract(clustering_method, ",.*$") %>%
           str_remove(., "^,") %>%
           factor(., levels = c("30", "50", "100")),
         clustering_method = 
           str_extract(clustering_method, "^.*,") %>%
           str_remove(., "Seurat\\.") %>%
           str_remove(., ",$") %>%
           str_replace(., "_", "."))

SC3 <- read_single_method("SC3") %>%
         mutate(level = as.numeric(as.character(level)))

Monocle <- read_single_method(Method = "Monocle") %>% 
  mutate(level = str_remove(level, "^k_") %>% as.numeric()) %>%
  filter(level >= 10)
```

```{r all}
p1 <- ggplot(
  bind_rows(SC3 %>% select(-level),
            Monocle %>% select(-level),
            Seurat %>% select(-level)) %>%
    mutate(n_clus = (replicable_clusters + non_replicable_clusters) / 2) %>%
    filter(n_clus > 10),
  aes(x = n_clus, y = fraction_replicable_cells, col = clustering_name)) +
  geom_point(size = 3, alpha = .7) +
  my_theme() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = "Resolution", y = "Replicability", col = "Partitions") +
  scale_color_brewer(palette = "Set1") +
  guides(col = guide_legend(override.aes = list(alpha = 1))) +
  theme(legend.position = c(.8, .75),
        legend.title.align = 0.5,
        legend.title = element_text(size = 18),
        axis.title = element_text(size = 13),
        axis.text = element_text(size = 8),
        legend.text = element_text(size = 10))

p1
ggsave(filename = here("Figure-rep", "figures", "Rep-trade-off.png"), plot = p1,
       bg = "transparent", width = 7, height = 7)
```

```{r}
rm(p, SC3, Monocle, Seurat, read_single_method)
```

# Panel b

```{r}
source(here("Figure-Rep", "panel-b.R"))
df <- bind_rows(
  "Dune" = comp_dune(),
  "DE" = comp_DE_tree(),
  "Dist" = comp_Dist_tree(),
  .id = "Merge_method"
) %>%
  filter(clustering_name == "Seurat")
p2 <- ggplot(df %>% arrange(nb_clusters),
       aes(x = nb_clusters, y = fraction_replicable_cells, col = Merge_method)) +
  geom_line(aes(linetype = clustering_name), size = 2, alpha = .9,
            arrow = arrow(length = unit(0.30,"cm"), ends = "first", 
                          type = "closed"),
            show.legend = F) +
  geom_line(size = 0, alpha = 0) +
  scale_color_brewer(palette = "Dark2") +
  labs(x = "Resolution", y = "Replicability", col = "Method\nof Merging") +
  guides(color = guide_legend(
    override.aes = list(size = 3, alpha = 1))
  ) +
  my_theme() +
  annotate("text", x = max(df$nb_clusters) - 1,
           y = min(df$fraction_replicable_cells) + .01,
           label = "Start", fontface = "bold",
           size = 4) +
  scale_x_continuous(breaks = c(40, 45, 50, 55)) +
  theme(legend.position = c(.9, .8),
        legend.title.align = 0.5,
        legend.title = element_text(size = 18),
        axis.title = element_text(size = 13),
        axis.text = element_text(size = 8),
        legend.text = element_text(size = 10))
p2
ggsave(plot = p2, filename = here("Figure-Rep", "figures", "example.png"),
       bg = "transparent", width = 7, height = 7)
```

# Panel c

For now, this only include the brain data. It will also include the Pancreas data once it is ready

```{r}
df <- bind_rows(
  "Brain" = read.table(here("Figure-Rep", "data", "Brain.txt"), header = TRUE,
                       stringsAsFactors = FALSE),
  "Pancreas" = read.table(here("Figure-Rep", "data", "Pancreas.txt"),
                          header = TRUE, stringsAsFactors = FALSE),
  .id = "Contrast"
  ) %>%
  mutate(scenario = paste0(Contrast, "\n", method, "_", comp))
p3 <- ggplot(df %>% select(scenario, Merge_method, AUARIC) %>%
              group_by(scenario) %>%
              mutate(AUARIC = scale(AUARIC)),
            aes(x = scenario, y = Merge_method, fill = AUARIC)) +
  geom_tile() +
  scale_fill_viridis_c(begin = 1, end = 0) +
  my_theme() +
  theme(axis.text.x = element_text(angle = 90),
        axis.line = element_blank()) +
  labs(x = "", y = "", fill = "Scaled\nAUC",
       title = bquote("3 clustering methods × 3" ~ theta[method] ~
                        " × 2 pairs of datasets = 18 comparisons")) +
  theme(axis.text.y = element_text(size = 15),
        axis.text.x = element_text(size = 10),
        legend.title = element_text(size = 14, hjust = .5),
        legend.position = "bottom",
        title = element_text(size = 15))
p3
ggsave(plot = p3, filename = here("Figure-Rep", "figures", "all_comp.png"),
       width = 8, height = 3,
       bg = "transparent")
```

# Panel 

```{r}
# first align the top-row plot (p3) with the left-most plot of the
# bottom row (p1)
plots <- align_plots(p1, p3 + theme(legend.position = "bottom"),
                     align = 'v', axis = 'l')
# then build the top row
top_row <- plot_grid(plots[[1]], p2, labels = c('a)', 'b)'), label_size = 15,
                     scale = .9)

# then combine with the top row for final plot
p <- plot_grid(top_row, plots[[2]], labels = c('', 'c)'), label_size = 15,
               ncol = 1, rel_heights = c(2, 1.5))
save_plot(plot = p, 
          filename = here("Figure-Rep", "figures", "panel.png"),
          base_width = 12, base_height = 9,
          bg = "transparent")
```