---
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
title: 'Results on simulation data'
output:
  html_document:
    toc: true
    toc_float: TRUE
    toc_depth: 2
    number_sections: true
    code_download: TRUE
---

```{r load packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = F, message = F,
  fig.align = "center", echo = F
)
libs <- c("here", "dplyr", "ggplot2", "tidyr", "stringr", "readr", "cowplot",
          "mclust", "RColorBrewer", "purrr", "Dune", "pracma", "purrr",
          "DailyHRB", "patchwork")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
```

# Size Analysis

```{r}
df <- read.csv(here("Simulations", "Data", "Sizes.csv")) %>%
  select(-X, -Name) %>% 
  mutate(nCells = factor(nCells, levels = c(100, 200, 500, 1000, 2000, 5000))) %>%
  mutate(clustering = case_when(clustering == "sc3" ~ "SC3",
                                clustering == "tSNE_KMEANS" ~ "tSNE\nkmeans",
                                clustering == "UMAP_KMEANS" ~ "UMAP\nkmeans"))
p1 <- ggplot(df, aes(y = Value, x = level, col = nCells)) +
    geom_line() +
  facet_wrap(~clustering) +
  labs(col = "Number of cells", y ="ARI with ground truth", x = "Level of merging")
p1
df %>%
  filter(level == 100) %>%
  group_by(clustering) %>%
  arrange(nCells) %>%
  mutate(ratio = Value / dplyr::last(Value, order_by = nCells)) %>%
  select(nCells, ratio) %>%
  group_by(nCells) %>%
  summarise(mean_ratio = mean(ratio),
            min_ratio = min(ratio))
```

# Parameter Change Analysis

```{r}
df <- read.csv(here("Simulations", "Data", "Param.csv")) %>%
  select(-X, -Name) %>% 
  mutate(param = factor(param, levels = as.character(seq(30, 50, 5)))) %>%
  mutate(clustering = case_when(clustering == "sc3" ~ "SC3",
                                clustering == "tSNE_KMEANS" ~ "tSNE\nkmeans",
                                clustering == "UMAP_KMEANS" ~ "UMAP\nkmeans"))
p2 <- ggplot(df, aes(y = Value, x = level, col = param)) +
    geom_line() +
  facet_wrap(~clustering) +
  labs(col = "Parameter value", y ="ARI with ground truth", x = "Level of merging")
p2
```

# Number of Methods Analysis

```{r}
df <- read.csv(here("Simulations", "Data", "Ns.csv")) %>%
  select(-X, -Name) %>% 
  # filter(clustering %in% c("sc3_40", "X40", "X40.1")) %>%
  mutate(clustering = case_when(clustering == "X40" ~ "UMAP_KMEANS_40",
                                clustering == "X40.1" ~ "tSNE_KMEANS_40",
                                TRUE ~ clustering)) %>%
  mutate(param = word(clustering, -1, sep = "_"),
         clustering = word(clustering, 1, sep = "_")) %>%
         # clustering = str_remove(clustering, "_40")) %>%
  mutate(ns = word(ns, 1, sep = "_")) %>%
  group_by(level, clustering, param, ns) %>%
  summarise(Value = mean(Value)) %>%
  mutate(clustering = case_when(clustering == "sc3" ~ "SC3",
                                clustering == "tSNE" ~ "tSNE\nkmeans",
                                clustering == "UMAP" ~ "UMAP\nkmeans"),
         param  = paste0("K = ", param))
p3 <- ggplot(df, aes(y = Value, x = level, col = ns)) +
    geom_line() +
  facet_wrap(~clustering + param, ncol = 5) +
  labs(col = "Number of\nmethods used\nas input", y ="ARI with ground truth",
       x = "Level of merging") +
  guides(col = guide_legend(ncol = 2)) +
  theme_classic() +
  theme(plot.background = element_rect(fill = "transparent",
                                       colour = "transparent"),
        legend.background = element_rect(fill = "transparent"),
        strip.background = element_rect(fill = "transparent"),
        panel.background = element_rect(fill = "transparent"),
        legend.position = c(.92, .3),
        strip.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 8),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12)) +
  scale_y_continuous(limits = c(.5, 1), breaks = c(0, .5, 1)) +
  scale_x_continuous(breaks = c(0, 50, 100), labels = c("0%", "50%", "100%"))
p3
```
# All together

```{r}
plots <- list(p1, p2)
plots <- lapply(plots, function(p) {
  p <- p + 
      theme_classic() +
  theme(plot.background = element_rect(fill = "transparent",
                                       colour = "transparent"),
        legend.background = element_rect(fill = "transparent"),
        strip.background = element_rect(fill = "transparent"),
        panel.background = element_rect(fill = "transparent"),
        legend.position = "bottom",
        strip.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 8),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12)) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, .5, 1)) +
  scale_x_continuous(breaks = c(0, 50, 100), labels = c("0%", "50%", "100%")) +
  guides(col = guide_legend(nrow = 1))
  return(p)
})
first_row <- plot_grid(plotlist = plots, nrow = 1, scale = .9,
               labels = c("a)", "b)"), label_size = 16)
second_row <- plot_grid(p3, nrow = 1, scale = .9,
               labels = c("c)"), label_size = 16)
p <- plot_grid(first_row, second_row, nrow = 2)
p
ggsave(filename = here("Simulations", "Figures", "Robustness.png"),
       bg = "transparent", plot = p, width = 11, height = 10)
```


# Variance

```{r}
df1 <- read.csv(here("Simulations", "Data", "Ns.csv")) %>%
  select(-X, -Name) %>% 
  filter(clustering %in% c("sc3_40", "X40", "X40.1")) %>%
  mutate(clustering = case_when(clustering == "X40" ~ "UMAP_KMEANS_40",
                                clustering == "X40.1" ~ "tSNE_KMEANS_40",
                                TRUE ~ clustering),
         clustering = str_remove(clustering, "_40")) %>%
  mutate(ns = factor(ns)) %>%
  mutate(clustering = case_when(clustering == "sc3" ~ "SC3",
                                clustering == "tSNE_KMEANS" ~ "tSNE\nkmeans",
                                clustering == "UMAP_KMEANS" ~ "UMAP\nkmeans")) %>%
  filter(level %in% c(0, 100)) %>%
  group_by(ns, level) %>%
  summarise(var = var(Value)) %>%
  dplyr::rename("Param" = "ns")
df2 <- read.csv(here("Simulations", "Data", "Param.csv")) %>%
  select(-X, -Name) %>% 
  mutate(param = factor(param, levels = as.character(seq(30, 50, 5)))) %>%
  mutate(clustering = case_when(clustering == "sc3" ~ "SC3",
                                clustering == "tSNE_KMEANS" ~ "tSNE\nkmeans",
                                clustering == "UMAP_KMEANS" ~ "UMAP\nkmeans")) %>%
  ungroup() %>%
  filter(level %in% c(0, 100)) %>%
  group_by(param, level) %>%
  summarise(var = var(Value)) %>%
  dplyr::rename("Param" = "param")
df3 <- read.csv(here("Simulations", "Data", "Sizes.csv")) %>%
  select(-X, -Name) %>% 
  mutate(nCells = factor(nCells, levels = c(100, 200, 500, 1000, 2000, 5000))) %>%
  mutate(clustering = case_when(clustering == "sc3" ~ "SC3",
                                clustering == "tSNE_KMEANS" ~ "tSNE\nkmeans",
                                clustering == "UMAP_KMEANS" ~ "UMAP\nkmeans")) %>%
  filter(level %in% c(0, 100)) %>%
  group_by(nCells, level) %>%
  summarise(var = var(Value)) %>%
  dplyr::rename("Param" = "nCells")
df4 <- lapply(1:6, function(id){
  df <- read.csv(here("Simulations", "Data", paste0("Metric_Ref_", id, ".csv")))
  return(df)
}) %>% 
  bind_rows(., .id = "Dataset") %>%
  filter(method != "param", as.numeric(level) %in% c(0, 100),
         method == "Dune_NMI", Metric == "ARI") %>%
  group_by(Dataset, level)  %>%
  summarise(var = var(Value)) %>%
  dplyr::rename("Param" = "Dataset")
  

df <- bind_rows(
  "ns" = df1,
  "param" = df2,
  "nCells" = df3,
  "stopping" = df4,
  .id = "type"
)
df <- df %>% 
  mutate(level = if_else(level == 0, "Initial", "Final")) %>%
  pivot_wider(names_from = level, values_from = var) %>%
  mutate(change = Final / Initial)
mean(df$change)
mean(df$change > 1)
sum(df$change > 1)
```