---
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
title: 'Results on simulation data'
output:
  html_document:
    toc: true
    toc_float: TRUE
    toc_depth: 2
    number_sections: true
    code_download: TRUE
---

```{r load packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = F, message = F,
  fig.align = "center", echo = F
)
libs <- c("here", "dplyr", "ggplot2", "tidyr", "stringr", "readr", "cowplot",
          "mclust", "RColorBrewer", "purrr", "Dune", "pracma", "purrr",
          "DailyHRB", "patchwork")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
```

# Input vs Output 

```{r}
df <- read.csv(here("Simulations", "Data", "Imp.csv")) %>%
  select(-X, -Name, -n_clus) %>%
  filter(level %in% c(0, 100)) %>%
  mutate(level = if_else(level == 0, "Initial","Final")) %>%
  pivot_wider(names_from = "level", values_from = "Value") %>%
  mutate(
    clustering = case_when(
      str_detect(clustering, ".1") ~ "tSNE",
      str_detect(clustering, "X") ~ "UMAP",
      TRUE~ "sc3"),
    Improvement = Final - Initial
  ) %>%
  filter(nCells > 200) %>%
  pivot_longer(c("Initial", "Final", "Improvement"), names_to = "Type",
               values_to = "ARI") %>%
  mutate(param = as.factor(param),
         Type = factor(Type, levels = c("Initial", "Final", "Improvement")))

ggplot(df, aes(x = param, y = ARI, col = clustering)) +
  geom_boxplot() +
  labs(y = "ARI with ground truth", x = "Number of Initial clusters") +
  facet_wrap(~Type, ncol = 2, scales = "free") +
  theme_bw()+
  theme(legend.position = c(.75, .25),
        legend.direction = "horizontal")
```

```{r}
ggplot(df, aes(x = nCells, y = Final - Init, col = clustering)) +
  geom_point() +
  facet_wrap(~as.factor(param)) +
  labs(y = "Improvement") +
  theme_bw() 
```