---
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
title: 'Results on simulation data'
output:
  html_document:
    toc: true
    toc_float: TRUE
    toc_depth: 2
    number_sections: true
    code_download: TRUE
---

```{r load packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = F, message = F,
  fig.align = "center", echo = F
)
libs <- c("here", "dplyr", "ggplot2", "tidyr", "stringr", "readr", "cowplot",
          "mclust", "RColorBrewer", "purrr", "Dune", "pracma", "purrr",
          "DailyHRB", "patchwork")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
```

# Average silhouette width

```{r}
res <- lapply(1:6, function(id){
  df <- read.csv(here("Simulations", "Data", paste0("Metric_Ref_", id, ".csv")))
  return(df%>% filter(Metric == "SL"))
})
res <- bind_rows(res, .id = "Dataset")
ggplot(res, aes(x = n_clus, y = Value, col = clustering)) +
  geom_path() +
  theme_bw() +
  facet_grid(method ~Dataset, scales = "free")
```

# Results for all 40
## Finding where Dune stops

```{r}
res <- lapply(1:6, function(id){
  df <- read.csv(here("Simulations", "Data", paste0("Metric_Ref_", id, ".csv")))
  return(df)
})

min_ns <- lapply(res, function(df){
  df %>% filter(method %in% c("Dune", "Dune_NMI")) %>%
    group_by(method, clustering) %>%
    filter(n_clus == min(n_clus)) %>%
    select(method, n_clus, clustering) %>%
    distinct() %>%
    return()
}) %>% 
  bind_rows(.id = "Dataset") %>%
  mutate(method = if_else(str_detect(method, "NMI"), "NMI", "ARI"))
p <- ggplot(min_ns, aes(x = Dataset, y = n_clus, col = clustering)) +
  geom_jitter(width = .1, height = 0) +
  theme_bw() +
  facet_wrap( ~ method, ncol = 1) +
  scale_color_viridis_d() +
  labs(col = "Clustering", y = "Number of clusters") +
  geom_hline(yintercept = 30, col = "darkred") +
  annotate("text", y = 33, x = 4, label = "True number\nof clusters",
           col = "darkred")
p
```

## Comparison with the truth

```{r}
res <- bind_rows(res, .id = "Dataset") %>%
  filter(method != "param")
ggplot(res %>%
  filter(Metric != "SL") %>%
  filter(n_clus >= 20) %>%
  mutate(scenario = paste(Metric, str_remove(clustering, "_KMEANS"), sep = "_")),
  aes(x = n_clus, y = Value, col = method)) +
  facet_grid(Dataset ~ scenario, scales = "free") +
  geom_path() +
  theme_bw()
```

## Figure with paper

### A

```{r}
df <- res %>%
  filter(Metric == "ARI",
         Dataset == 2,
         method != "Dune",
         clustering == "TSNE_KMEANS",
         n_clus >= 10) %>%
  mutate(method = str_remove(method, "_NMI")) %>%
  arrange(n_clus) %>%
  select(n_clus, Value, method) %>%
  distinct()
p1 <- ggplot(df, aes(x = n_clus, y = Value, col = method)) +
  geom_line(size = 2, alpha = .9,
            arrow = arrow(length = unit(0.30,"cm"), ends = "first", 
                          type = "closed"),
            show.legend = FALSE) +
  geom_line(size = 0, alpha = 0) +
  my_theme() +
  labs(x = "Number of clusters", y ="ARI with ground truth",
       col = "Method\nof merging") +
  scale_color_brewer(palette = "Dark2") +
  guides(color = guide_legend(
    reverse = TRUE,
    title.position = "left",
    override.aes = list(size = 2, alpha = 1))
  ) +
  scale_y_continuous(limits = c(0, 1)) +
  theme(legend.title.align = 0.5,
        legend.title = element_text(size = 17),
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 10),
        legend.text = element_text(size = 12)) +
  annotate("text", x = 39, y = df$Value[df$n_clus == 40][1] + .08,
           label = "Start", fontface = "bold", size = 4)
p1 
```

### B

```{r}
p2 <- ggplot(res %>%
  filter(Metric != "SL") %>%
  filter(n_clus >= 20,
         method != "Dune",
         Dataset != 6,
         Metric == "ARI") %>%
  mutate(clustering = str_remove(clustering, "_KMEANS"),
         method = str_remove(method, "_NMI"),
         Dataset = paste("Dataset\n", Dataset)),
  aes(x = n_clus, y = Value, col = method)) +
  facet_grid(clustering ~ Dataset, scales = "free") +
  geom_line(size = 1, alpha = .9) +
  my_theme() +
  scale_x_continuous(breaks = c(20, 30, 40)) +
  theme(strip.background = element_rect(fill = "transparent")) +
  labs(x = "Number of clusters", y ="ARI with ground truth",
       col = "Method\nof merging") +
  scale_color_brewer(palette = "Dark2") +
  guides(color = FALSE)
p2
```

### C

```{r}
p3 <- ggplot(res %>%
  filter(Metric != "SL") %>%
  filter(n_clus >= 20,
         method != "Dune",
         Dataset != 6,
         Metric == "NMI") %>%
  mutate(clustering = str_remove(clustering, "_KMEANS"),
         method = str_remove(method, "_NMI"),
         Dataset = paste("Dataset\n", Dataset)),
  aes(x = n_clus, y = Value, col = method)) +
  facet_grid(clustering ~ Dataset, scales = "free") +
  my_theme() +
  theme(strip.background = element_rect(fill = "transparent")) +
  geom_line(size = 1, alpha = .9) +
  labs(x = "Number of clusters", y ="NMI with ground truth",
       col = "Method\nof merging") +
  scale_x_continuous(breaks = c(20, 30, 40)) +
  scale_color_brewer(palette = "Dark2") +
  guides(color = FALSE)
p3
```
### All

```{r}
first_row <- plot_grid(NULL, p1, NULL, nrow =  1, labels = c("", "a)", ""),
                       label_size = 18, scale = .9, rel_widths = c(.1, .8, .1))
second_row <- plot_grid(p2, p3, nrow =  1, labels = c("b)", "c)"),
                           label_size = 18, scale = .9)
p <- plot_grid(first_row, second_row, nrow = 2)
p
save_plot(filename = here("Simulations", "Figures", "Simu_1.png"),
          plot = p, base_height = 6, base_width = 10, bg = "transparent")
```

```{r}
legend <- get_legend(p1 + theme(legend.position = "bottom") +
                       labs(col = "Method of merging"))
first_row <- plot_grid(p1 + guides(col = FALSE), p2, nrow =  1, labels = c("a)", "b)"),
               label_size = 18, scale = .9)
second_row <- plot_grid(NULL, legend, NULL, rel_widths = c(.4, .2, .4), nrow = 1)
p <- plot_grid(first_row, second_row, nrow = 2, rel_heights = c(.8, .1))
p
save_plot(filename = here("Simulations", "Figures", "Simu_2.png"),
          plot = p, base_height = 6, base_width = 10, bg = "transparent")
```